.gitignore, Core/Main/PTMagic.cs, Monitor/Pages/SettingsAnalyzer.cshtml, Monitor/Pages/SettingsGeneral.cshtml, Monitor/Pages/SettingsGeneral.cshtml.cs, Monitor/Pages/_get/BagDetails.cshtml, PTMagic/PTMagic.csproj
This PR Contains the following changes:
-Added a Log Message on Market Data Update if no CMC Key was provided
-Made the Tradingview Window Larger
-Updated the 3rd Party Packages to their Latest Stable Version
-Included CMC API Key in Settings Web Frontend
-Settings General and Settings Analyzer are now collapsible
=> Multiple Changes

Core/MarketAnalyzer/Binance.cs
Filtered out bad Binance API data.
=> Binance API bad market fix

PTMGitCommands.bat
Added a Script to sync up your fork with master.
More options will follow in the future.
=> Add Git Sync Command

Core/Main/PTMagic.cs, Core/ProfitTrailer/SettingsAPI.cs
Saving settings in PT2.2 is working again.
=> Setting Save for PT2.2

Core/DataObjects/PTMagicData.cs, Core/DataObjects/ProfitTrailerData.cs, Core/Main/PTMagic.cs, Core/MarketAnalyzer/CoinMarketCap.cs, Core/ProfitTrailer/SettingsAPI.cs, Core/ProfitTrailer/SettingsHandler.cs, Monitor/Pages/BagAnalyzer.cshtml.cs, Monitor/Pages/BuyAnalyzer.cshtml.cs, Monitor/Pages/DCACalculator.cshtml, Monitor/Pages/DCACalculator.cshtml.cs, Monitor/Pages/SalesAnalyzer.cshtml.cs, Monitor/Pages/SettingsGeneral.cshtml, Monitor/Pages/StatusSummary.cshtml, Monitor/Pages/_get/BagDetails.cshtml.cs, Monitor/Pages/_get/BagList.cshtml.cs, Monitor/Pages/_get/BuyList.cshtml.cs, Monitor/Pages/_get/DashboardBottom.cshtml.cs, Monitor/Pages/_get/DashboardTop.cshtml.cs, Monitor/Pages/_get/SalesList.cshtml.cs, Monitor/Pages/_get/TickerWidgets.cshtml.cs, PTMagic/_defaults/_default settings PT 2.x/_default settings BTC or ETH/settings.general.json, PTMagic/_defaults/_default settings PT 2.x/_default settings USDT/settings.general.json, _Development/DevSettings/settings.general.json
Update to support PT 2.2
Removed some now unnecessary lines in settings.general.
Added one line in settings.general for Server API Token.
Removed PT1 backwards compatibility.
=> (WIP) PT2.2 Changes

Core/DataObjects/PTMagicData.cs, Core/DataObjects/ProfitTrailerData.cs, Core/Helper/SystemHelper.cs, Core/Main/PTMagic.cs, Core/ProfitTrailer/StrategyHelper.cs, Monitor/Pages/_get/BagDetails.cshtml, Monitor/Pages/_get/DashboardBottom.cshtml, Monitor/Pages/_get/DashboardTop.cshtml, PTMagic/_defaults/_default settings PT 2.x/_default settings BTC or ETH/settings.general.json, PTMagic/_defaults/_default settings PT 2.x/_default settings USDT/settings.general.json
- Removed left-over code from fiat value in Dashboard top
- Increase Startup Timer total and interval - retry every 10 seconds for 4 minutes
- Added last 30days to dashboard sales widget
- Added option for up to 4 Indicators in bag analyzer TV widget
=> Monitor Changes

Core/DataObjects/PTMagicData.cs, Core/DataObjects/ProfitTrailerData.cs, PTMagic/_defaults/_default settings PT 2.x/_default settings BTC or ETH/settings.general.json, PTMagic/_defaults/_default settings PT 2.x/_default settings USDT/settings.general.json, _Development/DevSettings/settings.general.json
Some more changes in the Datastructure i missed earlier
=> Data Structure Changes

Core/ProfitTrailer/StrategyHelper.cs
updated monitor icons for DMA, HMA, and PDHIGH
=> New PT strategy icons

Core/DataObjects/PTMagicData.cs, Core/Main/PTMagic.cs, Core/MarketAnalyzer/BaseAnalyzer.cs, Monitor/Pages/SettingsGeneral.cshtml.cs
Reverts PTMagicians/PTMagic#57
Force presets update error.
=> Revert "Minor Fixes"

Core/Main/PTMagic.cs
Small Change that should make our life a lot easier.
=> Added Clearer Log Message

_Development/README.md
Reverts PTMagicians/PTMagic#65
=> Revert "Update _Development/README.md"

Core/Main/PTMagic.cs
Reverts PTMagicians/PTMagic#64
=> Revert "Added Clearer Log Message"

Monitor/Pages/BagAnalyzer.cshtml, Monitor/Pages/_get/BagList.cshtml, Monitor/Pages/_get/DashboardTop.cshtml, Monitor/wwwroot/assets/css/custom.css
Re-PR of https://github.com/PTMagicians/PTMagic/pull/76
=> Badders' highlight pairs without average price

Core/DataObjects/ProfitTrailerData.cs, Core/MarketAnalyzer/Binance.cs, Core/MarketAnalyzer/Bittrex.cs, Core/MarketAnalyzer/Poloniex.cs
Improved the performance of creating the PT data sets for polling and significantly improved getting market ticks process using parallelism.
=> Performance improvements using parallelism

Monitor/Pages/_Layout.cshtml, Monitor/Pages/_get/DashboardTop.cshtml, _Development/Update Notes Template.txt
- Added a template for update notes to _Development
- changed the dashboard tooltip for "Values" to enhance clarity
=> Update Notes Template

Core/Main/PTMagic.cs
Good news is that retesting #55 on Unix all is good. I had a deployment issue for the previous test
=> Added extra logging for detected settings changes

Core/Main/PTMagic.cs
Exit PTM after Config Error Message
=> Exit PTM after Config Error Message

Core/MarketAnalyzer/Poloniex.cs
Fixed incorrect exchange in Poloniex.cs
=> Poloniex Market Ticks

Monitor/Pages/SettingsGeneral.cshtml
Re-submissions of https://github.com/PTMagicians/PTMagic/pull/94
I accidentally did a re-base before the PR was merged.   ;)
=> Additional Gui Fields

Monitor/Pages/BuyAnalyzer.cshtml, Monitor/Pages/_get/BuyList.cshtml, Monitor/Pages/_get/DashboardTop.cshtml
Added a column for 24h trend to the possible buy list in the monitor.
=> 24h Trend for Possible Buy

Core/ProfitTrailer/SettingsHandler.cs
Removed from file header:
####### PTMagic Current Setting ########
=> Removed redundant header comment

Core/Helper/SystemHelper.cs, Monitor/Pages/MarketAnalyzer.cshtml, Monitor/Pages/SalesAnalyzer.cshtml, Monitor/Pages/SalesAnalyzer.cshtml.cs, Monitor/Pages/StatusSummary.cshtml, Monitor/Pages/_get/TickerWidgets.cshtml, Monitor/wwwroot/assets/css/custom.css
- added main market price and ticker to market analyzer page
- added start balance, estimated current balance to sales analyzer page
- added cumulative sales chart to sales analyzer page
- increased PTM health warning timer slightly
=> Multiple Monitor Changes

Monitor/Pages/SalesAnalyzer.cshtml
Altered the layout in the Sales Analyzer page for Current and Starting balance
=> Sales Analyzer layout

Core/ProfitTrailer/SettingsHandler.cs, Core/ProfitTrailer/StrategyHelper.cs, Monitor/Pages/SalesAnalyzer.cshtml.cs, Monitor/Pages/_Layout.cshtml, Monitor/Pages/_get/DashboardTop.cshtml
tweaked the dashboard baglist to help a bit more with smaller screens.
added "rebuy timeout" strategy shortcut
=> Gui Tweaks and more OFFSETPERCENT integer fixes

Monitor/Pages/_Layout.cshtml
Moved "contribute" to a new location on the wiki:
https://github.com/PTMagicians/PTMagic/wiki/Contribute
=> Update Donate Link

Core/ProfitTrailer/StrategyHelper.cs
Added new strategy shortcuts for:
- Buy/Sell Formula
- Rebuy Timeout
- min/max  change perc
=> Strategy Icons

Core/ProfitTrailer/StrategyHelper.cs
~~Added code which will allow users to flag their custom strategies so they indicate true/false correctly.~~
~~Custom strategy labels should start (or end) with an asterisk.~~
~~(Another symbol might be better?)~~
=> Custom Strategies and Formula Fix

Core/Main/PTMagic.cs
- altered frozen process message for clarity, and to include suggested remedies.
=> Frozen process check and message

Core/DataObjects/ProfitTrailerData.cs, Monitor/Pages/SalesAnalyzer.cshtml, Monitor/Pages/_get/DashboardBottom.cshtml, Monitor/Pages/_get/DashboardBottom.cshtml.cs, Monitor/Pages/_get/DashboardTop.cshtml, PTMagic/Program.cs
- added "Daily" to chart Y axis for clarity
- added a new "Asset Distribution" chart to the dashboard
- ~~moved "sales overview" to column bottom~~
- ~~reduced daily profits chart on dashboard from 30 days to 10 days~~
- ~~resized dashboard trend chart to line up with the bottom of "sales overview"~~
=> Charts update

Core/DataObjects/ProfitTrailerData.cs, Monitor/Pages/SalesAnalyzer.cshtml, Monitor/Pages/_get/DashboardBottom.cshtml, Monitor/Pages/_get/DashboardBottom.cshtml.cs, Monitor/Pages/_get/DashboardTop.cshtml
- added account value to asset pie-chart
- removed dust from asset pie-chart
- minor edits for account value on sales analyzer page
- removed a few lines of unused code
- added pending coins to the pair & DCA list
- changed the title of the Pairs & DCA list to Pairs/DCA/Pending
=> Monitor edits & Pending

Core/ProfitTrailer/StrategyHelper.cs
- added code to parse formulas and return a red/green shortcut
=> Formula Parsing

Core/DataObjects/ProfitTrailerData.cs, Core/ProfitTrailer/StrategyHelper.cs, Monitor/Pages/_get/DashboardBottom.cshtml
Added coins held in PT "Watchmode" (trading disabled, but not hidden) to the pairs/dca/pending list.
=> Watchmode Coins

Monitor/Pages/_get/DashboardBottom.cshtml.cs
Issue was with how the data was being put together for the pie chart of asset distribution. The values were not quoted but in certain locals the number is rendered with commas instead of periods and therefore caused a JS rendering error. Simple fix of adding quotes.
=> Fixed issue #133

Monitor/Pages/_get/DashboardBottom.cshtml.cs, PTMagic/Program.cs
=> Version increment

Core/DataObjects/ProfitTrailerData.cs, Core/Helper/SystemHelper.cs, Core/Main/PTMagic.cs, Core/MarketAnalyzer/BaseAnalyzer.cs, Core/MarketAnalyzer/Binance.cs, Core/MarketAnalyzer/BinanceUS.cs, Core/ProfitTrailer/SettingsAPI.cs, Core/ProfitTrailer/SettingsFiles.cs, Core/ProfitTrailer/StrategyHelper.cs, Monitor/Pages/BagAnalyzer.cshtml, Monitor/Pages/BagAnalyzer.cshtml.cs, Monitor/Pages/BuyAnalyzer.cshtml.cs, Monitor/Pages/DCACalculator.cshtml.cs, Monitor/Pages/MarketAnalyzer.cshtml, Monitor/Pages/SalesAnalyzer.cshtml, Monitor/Pages/SalesAnalyzer.cshtml.cs, Monitor/Pages/SettingsGeneral.cshtml, Monitor/Pages/_get/BagDetails.cshtml.cs, Monitor/Pages/_get/BagList.cshtml.cs, Monitor/Pages/_get/BuyList.cshtml.cs, Monitor/Pages/_get/DashboardBottom.cshtml, Monitor/Pages/_get/DashboardBottom.cshtml.cs, Monitor/Pages/_get/DashboardTop.cshtml, Monitor/Pages/_get/DashboardTop.cshtml.cs, Monitor/Pages/_get/SalesList.cshtml.cs, Monitor/_Internal/BasePageModel.cs, Monitor/_Internal/BasePageModelSecure.cs, Monitor/wwwroot/assets/js/analyzer-settings.js, PTMagic/Program.cs, _Development/Update Notes Template.txt
=> PT API v2 and Binance US

Monitor/Pages/SettingsGeneral.cshtml.cs
- Removed ability to change Exchange and timzone offset via GUI
=> Fix for Issue #142

Core/Main/PTMagic.cs, Monitor/Monitor.csproj, Monitor/Program.cs, Monitor/nlog.config, PTMagic/Program.cs
These changes will log any errors on any thread that aren't handled which will help with fault finding
=> Added unhandled exception logging to Core and Monitor

Monitor/Logger.cs, Monitor/Pages/Error.cshtml, Monitor/Pages/Error.cshtml.cs, Monitor/Pages/MarketAnalyzer.cshtml.cs, Monitor/Program.cs, Monitor/Startup.cs
Updated logging to ensure exceptions are logged in the Monitor ASP.Net Core app
=> Added ASP.Net Core exception logging

Monitor/Pages/SettingsAnalyzer.cshtml.cs
Fixes issue with saving settings on the Analyser settings page
=> Increase form limits to allow complex settings

Core/Main/PTMagic.cs, Monitor/Pages/Error.cshtml, Monitor/Pages/Error.cshtml.cs
- Re-added code to show Error details on HTML page.
- Removed old DCA Calculator debug code.
=> Display Error on page

Core/ProfitTrailer/StrategyHelper.cs
Fixed mistakes and renamed a few for clarity.
=> Shortcut Changes

Core/Helper/SystemHelper.cs, Core/Main/PTMagic.cs, Core/MarketAnalyzer/BaseAnalyzer.cs, Core/MarketAnalyzer/BinanceFutures.cs, Monitor/Pages/_get/DashboardTop.cshtml, PTMagic/Program.cs, _Development/CreateRelease.cmd
- added support for Binance Futures
- set version to 2.4.0
=> Binance Futures

Core/ProfitTrailer/StrategyHelper.cs
- added strategy shortcut for "LEVERAGE (X)"
=> Leverage Shortcut

Core/DataObjects/PTMagicData.cs, Core/DataObjects/ProfitTrailerData.cs, Monitor/Pages/MarketAnalyzer.cshtml, Monitor/Pages/SettingsGeneral.cshtml, Monitor/Pages/SettingsGeneral.cshtml.cs, PTMagic/_defaults/_default settings PT 2.x/settings.general.json
- fixed profit calculations for short positions
- Added option to change base currency chart on Market Analyzer page
=> Shorting calculations & analyzer chart

PTMagic/Program.cs
=> increment version

Core/DataObjects/ProfitTrailerData.cs
- fixed invalid check for short position profit calculations
=> Fix profit calculation

PTMagic/Program.cs, PTMagic/_defaults/_default settings PT 2.x/settings.general.json, _Development/DevSettings/settings.general.json
- a few fixes to the default settings
=> settings fix

Core/DataObjects/PTMagicData.cs, Core/DataObjects/ProfitTrailerData.cs, Monitor/Pages/_get/DashboardBottom.cshtml, Monitor/Pages/_get/DashboardBottom.cshtml.cs, Monitor/Pages/_get/DashboardTop.cshtml
Exposed the buy volume data to the UI via the model. Fixed layout issues in the buy log and in the asset distribution.
=> Fixed UI issues, exposed buy volume data

Monitor/Pages/_get/DashboardTop.cshtml
- minor typo fixed:  volume24 > volume24h
=> fixed dashboartop volume24h typo

Monitor/Pages/_get/DashboardBottom.cshtml, Monitor/Pages/_get/DashboardTop.cshtml
- PBL column adjustments
- New tooltips and minor layout adjustments to distribution panel
=> minor GUI adjustments

Monitor/Pages/SalesAnalyzer.cshtml, Monitor/Pages/SalesAnalyzer.cshtml.cs, Monitor/Pages/_get/DashboardBottom.cshtml, Monitor/Pages/_get/DashboardBottom.cshtml.cs, Monitor/Pages/_get/DashboardTop.cshtml, Monitor/Pages/_get/DashboardTop.cshtml.cs
- Numerous changes to calculate profits correctly, particularly when using leverage, and shorting.
=> Changes to profit calculations

Core/MarketAnalyzer/BinanceUS.cs
=> Binance USD market error

Monitor/Pages/ManageSMS.cshtml, Monitor/Pages/ManageSMS.cshtml.cs, Monitor/Pages/_Layout.cshtml, Monitor/Pages/_get/TickerWidgets.cshtml, PTMagic/Program.cs
* adjusted columns and for better readability
* added SMS counts
=> Page: Manage Single Market Changes

Core/MarketAnalyzer/BaseAnalyzer.cs
Fixes issue with building trends when new pairs are present and they have no data in the trend as reported by @HojouFotytu
=> Fixed KeyNotFoundException when building trends

Core/DataObjects/PTMagicData.cs, Core/Helper/SystemHelper.cs, Core/Main/PTMagic.cs, Core/MarketAnalyzer/BaseAnalyzer.cs, Core/ProfitTrailer/StrategyHelper.cs, Monitor/Pages/MarketAnalyzer.cshtml, Monitor/Pages/SettingsAnalyzer.cshtml.cs, Monitor/Pages/_get/DashboardBottom.cshtml, Monitor/Pages/_get/DashboardTop.cshtml, Monitor/Pages/_get/TickerWidgets.cshtml
- minor resize of dashboard bottom charts
- fixed an error where underscore was added to Binance Futures coin pairs (issue #230)
=> Enabled Pairs & Ignore Outliers

PTMagic/PTMUpdate.sh
Added a Script which allows for easy version switching on linux.
=> Auto Update Script for Linux

Core/Main/PTMagic.cs, Monitor/Pages/MarketAnalyzer.cshtml, Monitor/Pages/_get/DashboardTop.cshtml, Monitor/Pages/_get/SettingsMarketTrends.cshtml
- leverage wasn't being included in calculation for individual pair profits nor total bag gain, when using gainStrategy value
=> leveraged profits fix

Core/Helper/SystemHelper.cs, Monitor/Pages/_get/BagDetails.cshtml
Updated to use the latest Trading View chart widget which stops the weird looping we see calling TradingView at the moment.
=> Fixed TradingView chart flashing in the bag details pop-up

Monitor/Pages/_get/DashboardBottom.cshtml.cs
=> Leverage calculations issues fixed for distibution chart

Monitor/Pages/_get/DownloadFile.cshtml.cs, Monitor/Startup.cs, Monitor/_Internal/BasePageModelSecure.cs, Monitor/_Internal/BasePageModelSecureAJAX.cs
- Downloaded data is now steamed instead of being redirected to in the assets folder
- Old assets/tmp folder removed on start up for security
- Fixes issues where the download page could be used without authenticating first
=> Fixes security issues around configuration download

Core/Main/PTMagicConfiguration.cs, Monitor/Pages/SettingsGeneral.cshtml, Monitor/Pages/SetupPassword.cshtml, Monitor/Pages/SetupPassword.cshtml.cs
Properly mask the ServerAPIToken in the web interface
fix check if password and confirm are identical
=> Some more Security Improvements

Monitor/Pages/SettingsGeneral.cshtml, Monitor/Pages/SetupPassword.cshtml, Monitor/Pages/SetupPassword.cshtml.cs
- Password file path was missing a "/" separator:
File check was returning false when it shouldn't
Old password check logic was accepting anything for old password
- Added "Change Password" with a link to SetupPassword page.
- Altered some tooltips for General Settings
=> Password file check

Core/Helper/SystemHelper.cs, Monitor/Pages/_get/DashboardTop.cshtml
Added age column to the bags overview ticker so that you can see how long bag have been open with ease.
=> Added age column to bags

Monitor/Pages/SettingsAnalyzer.cshtml.cs, Monitor/Pages/_get/SettingsSingleMarketSettings.cshtml, PTMagic/Program.cs
- Added GUI fields to SettingsSingleMarketSettings for IgnoredGlobalSetting and AllowedGlobalSettings
=> SMS ignored/allowed markets

Core/Helper/SystemHelper.cs, Monitor/Pages/_get/DashboardTop.cshtml
Made some tweaks to BagAge on dashboard:
- Age > 1d doesn't display minutes (unless hours = 0)
- Age > 1h doesn't display seconds (unless minutes = 0)
- removed unused variable "shortValue"
Fixed SMS icon wrapping in both PBL and PAIRS
=> age tweaks

Core/Main/PTMagic.cs
A line change for SMS ignored/allowed logic was added to the incorrect section of the code.  This was fixed.
=> Fixed incorrect line change

Core/MarketAnalyzer/BaseAnalyzer.cs
Changes for SMS Ignored/Allowed substring check duplicated for Market Trends Ignored/Allowed.
=> Ignored/Allowed substring for Market Trends

Core/Main/PTMagic.cs, Core/MarketAnalyzer/BaseAnalyzer.cs, PTMagic/Program.cs
- Fixed a bug that prevented Ignored/Allowed markets to work correctly with the Poloniex exchange.
=> Poloniex ignored/allowed fix

Core/Helper/TelegramHelper.cs, Core/Main/PTMagic.cs, Core/MarketAnalyzer/BaseAnalyzer.cs, Core/MarketAnalyzer/Binance.cs, Core/MarketAnalyzer/BinanceFutures.cs, Core/MarketAnalyzer/BinanceUS.cs, Core/MarketAnalyzer/Bittrex.cs, Core/MarketAnalyzer/Poloniex.cs, Monitor/Pages/_get/BagDetails.cshtml
Market data building speed improvements and fix for supporting new Telegram library.
=> Speed improvements and compatibility update for Telegram

Core/ProfitTrailer/StrategyHelper.cs
Fixed an issue where conditional formulas were being incorrectly parsed by the StrategyHelper, and caused a display error on the Dashboard PBL and PAIRS list.
=> Conditional Formulas

Core/DataObjects/ProfitTrailerData.cs, Monitor/_Internal/BasePageModel.cs
Paged access to sales data for PT 2.5.x combability + bug fix where UI may clash with the last runtime data being written.
=> Paged access to sales data for PT 2.5.x combability + bug fix

Core/Core.csproj, Monitor/Monitor.csproj
Reverts PTMagicians/PTMagic#322
=> Revert "Bump Newtonsoft.Json from 12.0.3 to 13.0.2 in /Monitor"

Core/DataObjects/ProfitTrailerData.cs
Reverts PTMagicians/PTMagic#327
=> Revert "remove pending orders"

PTMagic/Program.cs
=> version number
