CONTRIBUTING.md
Core/MarketAnalyzer/BaseAnalyzer.cs
Core/ProfitTrailer/StrategyHelper.cs
Monitor/Pages/BagAnalyzer.cshtml
Monitor/Pages/DCACalculator.cshtml
Monitor/Pages/MarketAnalyzer.cshtml
Monitor/Pages/_Layout.cshtml
Monitor/Pages/_get/BagList.cshtml
Monitor/Pages/_get/DashboardBottom.cshtml
Monitor/Pages/_get/DashboardTop.cshtml
Monitor/wwwroot/assets/js/analyzer-settings.js

Changed all links to the new repository
Strategy helper: Added "MIN/MAX" for "Min/Max change pct" 
Strategy helper: changed "Max" to "DCAMAX" (avoid confusing with min/max)  
Strategy helper: Shortened "rebuy timeout"   to "TIMEOUT" 
Dashboard  -- Moved "value" to the left - removed dollar amount
Dashboard bottom - swapped sales & Market panels, so the entire page shows market data on the left, personal data on the right
Made Trend and Sales line charts a bit taller for better readability
Bag Analyzer heading -- changed "BT Value" to match PT:  "BSV - Buy Strategy Value"
Bag Analyzer heading  -- changed  "Buy Trigger"  to match PT:  "BST - Buy Strategy Target"
Bag Analyzer heading -- changed  "ST"  to match PT:   "SST - Sell Strategy Target"
Bag Analyzer heading  -- changed "Cost"  to …

Multiple Gui Changes

---

Core/DataObjects/PTMagicData.cs
Core/DataObjects/ProfitTrailerData.cs
Core/Main/PTMagic.cs
Core/MarketAnalyzer/CoinMarketCap.cs
Core/ProfitTrailer/SettingsAPI.cs
Core/ProfitTrailer/SettingsHandler.cs
Monitor/Pages/BagAnalyzer.cshtml.cs
Monitor/Pages/BuyAnalyzer.cshtml.cs
Monitor/Pages/DCACalculator.cshtml
Monitor/Pages/DCACalculator.cshtml.cs
Monitor/Pages/SalesAnalyzer.cshtml.cs
Monitor/Pages/SettingsGeneral.cshtml
Monitor/Pages/StatusSummary.cshtml
Monitor/Pages/_get/BagDetails.cshtml.cs
Monitor/Pages/_get/BagList.cshtml.cs
Monitor/Pages/_get/BuyList.cshtml.cs
Monitor/Pages/_get/DashboardBottom.cshtml.cs
Monitor/Pages/_get/DashboardTop.cshtml.cs
Monitor/Pages/_get/SalesList.cshtml.cs
Monitor/Pages/_get/TickerWidgets.cshtml.cs
PTMagic/_defaults/_default settings PT 2.x/_default settings BTC or ETH/settings.general.json
PTMagic/_defaults/_default settings PT 2.x/_default settings USDT/settings.general.json
_Development/DevSettings/settings.general.json

So this PR contains a lot of changes.
Removed the backwards compatibility with PT1.
The below settings are now removed from the settings file as this data now gets pulled via API.
"Exchange": "Bittrex",
"StartBalance": 0, 
"TimezoneOffset": "+0:00",
"MainFiatCurrency": "USD",
Added a new Setting to the settingsfile:
"ProfitTrailerServerAPIToken"
This has to be set to the same string in pt and ptm to allow comunication.
ProfitTrailerData is now being pulled via API and not via the file anymore. That's because this file doesn't exist anymore in PT2.2
PTM Functionality should work with PT2.2(Testing needed). Most Monitor pages are still not working. 
PT did some changes with the structure of their data. I already did some modifications but those data structure changes are most likely the …

PT 2.2 Unfinished Changes

---

Core/ProfitTrailer/SettingsHandler.cs

Removed auto-generated comments detailng specific trigger conditions from SMS, to help reduce file size.
PT2.2b34 has stricter size limitations for settings files.
Current SMS setting comments remain.

Removed SMS Trigger Comments

---

Core/DataObjects/PTMagicData.cs
Core/Main/PTMagic.cs
Core/MarketAnalyzer/BaseAnalyzer.cs
Monitor/Pages/SettingsGeneral.cshtml.cs

- Added FreeCurrencyConverterAPI key fix.
https://free.currencyconverterapi.com/ now requires users to obtain an API via email.
Added a new field to settings.general.json for this value.  It should work if the value is null.
If  "MainFiatCurrency":  is anything other than USD, an API key is required.
- Preset settings files are updated every run. 
Previously, changes to the preset files were only pushed to the API if the global settings changed -- or, if the user deleted the header of the config files in the PT config window exactly between PTM runs.   This made quickly updating settings impractical, often turning into a game of updating settings in multiple places and hoping they stuck.  Now settings can be updated via the local preset files, and they will be pushed every time PTM runs.

Minor Fixes

---

Core/DataObjects/PTMagicData.cs
Core/Main/PTMagic.cs
Core/MarketAnalyzer/BaseAnalyzer.cs
Monitor/Monitor.csproj

- Added FreeCurrencyConverterAPI key fix.
https://free.currencyconverterapi.com/ now requires users to obtain an API via email.
Added a new field to settings.general.json for this value.  It should work if the value is null.
If  "MainFiatCurrency":  is anything other than USD, an API key is required.
- Updated ASPNetCore 
"Microsoft.ApplicationInsights.AspNetCore" Version="2.5.1"
"Microsoft.AspNetCore.All" Version="2.1.7" 
"Microsoft.AspNetCore.Server.Kestrel" Version="2.1.3" 
"Newtonsoft.Json" Version="12.0.1"

CurrencyConverterAPI & AspNetCore Updates

---

CODE_OF_CONDUCT.md
Core/ProfitTrailer/StrategyHelper.cs
Monitor/Pages/_Layout.cshtml

- https://github.com/PTMagicians/PTMagic/issues/16
fix by @nnation 
- removed menu link to open PT monitor, and replaced it with a "Donate" button that takes the user to the donate section of the PTM wiki.
- updated code of conduct to remove reference to @Legedric

incorrect buy strats & donate button

---

Core/ProfitTrailer/SettingsHandler.cs

**Critical fix**
The changes @nnation put in for issue #72 changed all percentage offset calculations to integer regardless of the property type and therefore set all values to 0 usually. e.g.
I have adjusted the code so that if the property the percent offset is being applied to contains the word "timeout" it will use @nnation integer calculation, otherwise the original double calculation.

Fix for issue #72

---

Core/Helper/SystemHelper.cs
Core/Main/PTMagic.cs
Core/ProfitTrailer/SettingsFiles.cs
Core/ProfitTrailer/SettingsHandler.cs

Fixed issues where:
> Lines with a substring of the intended setting got processed
> Lines that are next to a misprocessed line are deleted
> Fixed issue where rendered lists always has a trailing separator
> Fixed issue with missing values for literals
Enhancements:
> Ensured file edit comments explain what is going on
> Added fix for #55 monitoring _preset files

Fixed issues where wrong lines were processed + minor UI fix for lists

---

Core/Main/PTMagic.cs
Core/ProfitTrailer/SettingsHandler.cs

The logic previously wasn't stopping global settings changes during the flood protection interval as it should of.

Fixed Flood Protection logic + house keeping

---

Core/Main/PTMagic.cs
Core/ProfitTrailer/SettingsFiles.cs
Core/ProfitTrailer/SettingsHandler.cs

This is a significant change as PTM now always regenerates the PT settings using the preset files and not by loading settings lines from PT. This change however simplifies the code and resolves issue #90 which is a significant issue.

Fix for issue #90 stops SMS settings getting stuck

---

Core/DataObjects/PTMagicData.cs
Core/Main/PTMagic.cs
Core/ProfitTrailer/SettingsHandler.cs
Monitor/Pages/SettingsGeneral.cshtml
Monitor/Pages/SettingsGeneral.cshtml.cs
PTMagic/_defaults/_default settings PT 2.x/_default settings BTC or ETH/settings.general.json
PTMagic/_defaults/_default settings PT 2.x/_default settings USDT/settings.general.json
_Development/DevSettings/settings.general.json

This fixes the issue @HojouFotytu raised when using the default settings with PTM 2.1.3
The issues stemmed from the default settings having empty empty properties sections for global settings e.g.
~~~
{
"SettingName": "ReadyForLiftOff",
"TriggerConnection": "AND",
"Triggers": [
{
"MarketTrendName": "1h",
"MinChange": 0.0
},
{
"MarketTrendName": "12h",
"MinChange": 0.0
},
{
"MarketTrendName": "24h",
"MaxChange": 3.0,
"MinChange": 1.0
}
],
"PairsProperties": {
"max_trading_pairs_OFFSET": 1,
"DEFAULT_trailing_buy_OFFSETPERCENT": -10,
"DEFAULT_A_sell_value_OFFSETPERCENT": 10
},
"DCAProperties": {
"DEFAULT_DCA_trailing_buy_OFFSETPERCENT": -10,
"DEFAULT_DCA_trailing_profit_OFFSETPERCENT": 10
},
"IndicatorsProperties": {}
}
~~~
This caused no lines to be loaded for processing and therefore threw …

Fixes for when settings have blank file properties

---

Core/ProfitTrailer/SettingsFiles.cs

This change stops PTM from writing file headers to your files in the _preset folder as it is unnecessary and potentially dangerous. On several occasions after shutting down PTM I have lost _preset file content as PTM was in the middle of writing the _preset file to add the comment block headers.
The files will remain untouched now and just a source for config; much safer.

Stop PTM writing file headers to preset files

---

Monitor/Pages/MarketAnalyzer.cshtml
Monitor/Pages/SalesAnalyzer.cshtml
Monitor/Pages/_Layout.cshtml
Monitor/Pages/_get/TickerWidgets.cshtml
Monitor/wwwroot/assets/css/custom.css
PTMagic/Program.cs

Altered the top ticker for better fit/functionality on mobile devices. 
- Moved TV (Total Value) to Sales Analyzer page
- Removed price of base currency
- Removed SMS count total
- Fixed a problem that prevented the current global setting from refreshing when it changed
- Slightly increased delay time check for PTM Health to reduce the number of false alarms
- The remaining ticker boxes (Global Setting and PTM Health) remain visible on small screens.

Ticker Changes

---

Core/Core.csproj
Core/DataObjects/PTMagicData.cs
Core/DataObjects/ProfitTrailerData.cs
Monitor/Pages/_get/BuyList.cshtml
Monitor/Pages/_get/DashboardTop.cshtml
PTMagic/PTMagic.csproj

Possible buys now orders buy:
> Trailing pairs
> True strategy pairs
> Number of true strategies descending
> SOM pairs
> 24hr percentage change
This gives the most useful to 10 pairs.
Also updated and cleaned up the Nuget references as we were using release candidate versions of Nlog and Telegram :0
Added % to the new 24h change column

Possible buys update + other minor tweaks

---

Core/DataObjects/PTMagicData.cs
Core/DataObjects/ProfitTrailerData.cs
Monitor/Pages/SalesAnalyzer.cshtml
Monitor/Pages/_get/DashboardTop.cshtml

- Changed PTM to use dynamic objects when loading PT data
- Current balance now uses the values from PT directly
- Tweaked possible buy sorting to ensure SOM pairs go to the bottom

Updated to use PT data for balance and buy order tweak

---

Core/MarketAnalyzer/Binance.cs
Core/ProfitTrailer/StrategyHelper.cs
Monitor/Pages/_get/DashboardTop.cshtml
PTMagic/Program.cs

- Fixes a problem where large values for StoreDataMaxHours causes PTM to exceed allowed binance requests per minute when gathering historical market data on the initial run.  #143 
- Added a shortcut for PT information "Sell Wall Detected" -> "WALL"
- Added a shortcut for PT information "Ignoring Buy Trigger" -> "TRIG"
- Changed tooltip for "Value" in pairs list to "Total Buy Value"

Excessive Requests

---

Core/DataObjects/ProfitTrailerData.cs
Core/Helper/SystemHelper.cs
Core/Main/PTMagic.cs
Core/MarketAnalyzer/BinanceUS.cs
Core/ProfitTrailer/StrategyHelper.cs
Monitor/Pages/BagAnalyzer.cshtml
Monitor/Pages/MarketAnalyzer.cshtml
Monitor/Pages/SettingsGeneral.cshtml
Monitor/Pages/_get/DashboardBottom.cshtml
Monitor/Pages/_get/DashboardTop.cshtml
Monitor/Pages/_get/DashboardTop.cshtml.cs
Monitor/wwwroot/assets/js/analyzer-settings.js

- created Monitor strategy shortcut "SOM" for new PT status: "config som enabled"
- fixed Monitor PBL sorting, broken by New PT status "config som enabled"
- Changed "Value" headers to "Cost" on Bag lists, since the value represents total cost, not current value.
- Added total cost and profit % on the bottom of dashboard bag list 
- Fixed broken links to PT wiki on Settings > Analyzer page.

Bag Totals, Bug Fixes, BinanceUS

---

Core/Main/PTMagic.cs
Core/ProfitTrailer/StrategyHelper.cs
Monitor/Pages/DCACalculator.cshtml
PTMagic/Program.cs

- Fixed DCA Calculator page freezing when no buy triggers found in the DCA.properties file. DCA_buy_triggers were deprecated in PT 2.4.2, replaced with the strategy PROFITPERCENTAGE. PTM now only uses PROFITPERCENTAGE in the DCA calculator.  See #158 
- Added new strategy shortcuts: changepercentage, pdlow, pdclose, lastdcabuy, fixedprice, lowatrband, highatrband, atrpercentage, profitpercentage, vwappercentage, mvwappercentage, btcdominance

DCA Calculator Bugfix

---

Core/ProfitTrailer/StrategyHelper.cs
Monitor/Pages/SettingsAnalyzer.cshtml
PTMagic/Program.cs

- Removed collapsing panels on the analyzer settings page, to address a bug caused by recent changes in java
- Removed "Upload Settings" option from the analyzer settings page.  It's been "coming soon"  for over a year -- the cake is a lie.
- Added strategy shortcut for "no dca buy logic"

Analyzer Settings GUI fix

---

.vscode/launch.json
Core/Core.csproj
Core/Main/PTMagic.cs
Core/MarketAnalyzer/BaseAnalyzer.cs
Core/MarketAnalyzer/Binance.cs
Core/MarketAnalyzer/BinanceUS.cs
Core/MarketAnalyzer/Bittrex.cs
Core/MarketAnalyzer/CoinMarketCap.cs
Core/MarketAnalyzer/Poloniex.cs
Core/ProfitTrailer/SettingsAPI.cs
Monitor/Monitor.csproj
Monitor/Pages/_get/DashboardTop.cshtml.cs
Monitor/Program.cs
Monitor/Startup.cs
PTMagic/PTMagic.csproj
PTMagic/Program.cs

This is a build that is upgraded to .Net Core 3.1 which is the LTS version of .Net Core and now recommended to be on for all .Net Core projects as security releases are stopping for 2.x
In addition I have upgraded to using HttpClient class for web service calls to try avoid the random thread hangs I have seen calling CoinMarketCap
I have flagged this as 3.0.0 as it is a major breaking change
.Net Core can be downloaded at https://dotnet.microsoft.com/download/dotnet-core/3.1

.Net 3.1 upgrade and web service call fix

---

Core/DataObjects/PTMagicData.cs
Core/DataObjects/ProfitTrailerData.cs
Core/ProfitTrailer/StrategyHelper.cs
Monitor/Pages/_get/DashboardBottom.cshtml
Monitor/Pages/_get/DashboardBottom.cshtml.cs
Monitor/Pages/_get/DashboardTop.cshtml

- Fixed issue #198 where Level formulas were crashing the monitor. Added code to make them compatible with the boolean parser, and added new shortcuts for level and level triggered formulas.
- Added shortcuts for a few new strategies
- Removed redundant refresh timers on dashboard bottom -- one timer should be enough.
- Reverted changes to distribution chart: starting balance and total gain make no sense on a chart designed to show current distribution of TCV.  Also, total gain is already visible at the bottom of the dashboard sales widget. Added starting balance to the bottom of the sales widget (makes more sense to have it here).

Level Forumulas, etc

---

Core/ProfitTrailer/StrategyHelper.cs
PTMagic/Program.cs

The parsing of formulas by PTM to present a "red" or "green" strategy icon in the PTM Monitor has been removed.  Standard formulas and level formulas will display as a standard yellow "information" icon. 
Maintaining a parsing engine within PTM to indicate the truth or falsity of the increasingly complex formulas available within PT simply isn't worth the development effort, considering it's overall usefulness to the average user.

removed formula parsing

---

Core/Main/PTMagicConfiguration.cs
Core/MarketAnalyzer/BaseAnalyzer.cs
Monitor/Pages/SettingsAnalyzer.cshtml.cs
Monitor/Pages/SettingsGeneral.cshtml.cs
Monitor/Pages/SetupPassword.cshtml.cs

Fixes issues where:
- When saving general or analyser settings not all setting took affect until PTM was restarted, they now do
- It was possible for PTM to get stuck not being able to calculate a trend for a pair, this is now fixed

Fixes for settings and trend data not refreshing

---

Monitor/Pages/SalesAnalyzer.cshtml
PTMagic/Program.cs

- Changed Balance Prediction on Sales Analyzer page to use TCV rather than current balance.
- update version to 2.5.1

Balance Prediction & Version update

---

Core/DataObjects/ProfitTrailerData.cs
Core/Main/PTMagic.cs
Core/ProfitTrailer/StrategyHelper.cs
Monitor/Pages/_get/DashboardBottom.cshtml
Monitor/Pages/_get/DashboardTop.cshtml
Monitor/Pages/_get/TickerWidgets.cshtml
Monitor/Pages/_get/TickerWidgets.cshtml.cs

Changes include:
- Add active single market settings to SMS tool tip
- Show profit % based on the GAIN strategy if available, this takes into account order book percentage if enabled
- Take into account TrendThreshold when calculating trend averages for SMS
- Fixed issues with PT 2.5 UI (beta) causing exceptions

Small enhancements including order book percentage, trend thresholds for SMS and fix for issues with PT 2.5 beta UI

---

Monitor/Pages/SalesAnalyzer.cshtml.cs
Monitor/wwwroot/assets/css/custom.css

Sales analyser is broken in the current build as the leverage calculation is causing a division by 0 issue if not using leverage, this fixes it.

Fixed TCV for sales analyser and tweaked font size for tables 

---

Core/Helper/SystemHelper.cs
Monitor/Pages/SalesAnalyzer.cshtml.cs
Monitor/Pages/SettingsGeneral.cshtml
Monitor/Pages/_get/DashboardBottom.cshtml.cs
PTMagic/Program.cs

- Fixed trading view LinkPlatform for exchanges other than BinanceFutures going to coin summary page rather than the chart
- Removed TradingViewFutures from LinkPlatform options.  Both spot and futures should now go to their correct charts when selecting "TradingView" for most exchanges
- Embedded TV charts now reference BinanceFutures coins correctly

Trading View & Distribution chart fixes

---

Core/DataObjects/PTMagicData.cs
Core/Main/PTMagic.cs
Core/Main/PTMagicConfiguration.cs
Monitor/Pages/SettingsGeneral.cshtml
PTMagic/_defaults/_default_settings_PT_2.x/settings.general.json
_Development/DevSettings/settings.general.json

- Removed the check for a local Profit Trailer path, and all references
- This will allow the use of PTM on a machine other than the one hosting Profit Trailer (eg., PT VPN subscribers)

Remove PT Path Check

---

Core/Main/PTMagicConfiguration.cs
Monitor/Pages/Login.cshtml.cs
Monitor/Pages/SettingsGeneral.cshtml
Monitor/Pages/SettingsGeneral.cshtml.cs
Monitor/Pages/_Layout.cshtml
Monitor/_Internal/BasePageModelSecure.cs

- The changes to allow the user to edit the masked API token won't work. If settings are saved (due to editing some other setting), the masked version of the API token is written to general.settings, which of course breaks the API access to PT. I reverted this to @JackTerok's first version, just showing an un-editable value like the license.
- Altered the masking method a bit, to encompass all possible lengths. PT has no minimum length for an API token, so the method has to account for a possible length of 1.  As written, anything under 4 characters would throw an error.
- When password is disabled and the Settings page is locked on the menu, users can now click "Settings" to go to the Login page.
- Logging on now changes the general.settings value for "PasswordEnabled" to true. This …

API Mask & unlock settings

---

Core/Main/PTMagic.cs
Core/MarketAnalyzer/BinanceFutures.cs

Changed the logic for the SMS parameters IgnoredMarkets & AllowedMarkets -- they now allow a partial string of the market to match for a trigger.
For example, if you want to ignore BTCUSDT you now only need to specify BTC.
The main reason for this was a significant problem trading Binance Futures that the Dev was unwilling to address.  See Issue #287 
All BTC quarterly futures positions (such as BTCUSDT_210326 and BTCUSDT_210625) can now be easily filtered by creating an SMS with "AllowedMarkets ": "BTC".   Even better, ALL current and future quarterly futures can be summarily ignored by filtering for "_" (underscore) since these are the only markets that have an underscore in their name.
However, users should be aware that any subset of a pair will cause a match.  For example, …

Ignored/Allowed in SMS && BinanceFutures Quarterly Contracts

---

Core/DataObjects/PTMagicData.cs
Core/ProfitTrailer/SettingsAPI.cs
Core/ProfitTrailer/SettingsHandler.cs
PTMagic/Program.cs
PTMagic/_defaults/_default_settings_PT_2.x/settings.general.json
_Development/DevSettings/settings.general.json

- added the ability to use a comma separated list of licenses and URLs in settings.general so that a single instance of PTM can update multiple PT bots.   When sending settings to multiple bots, they must all use the same ProfitTrailerServerAPIToken and ProfitTrailerDefaultSettingName
- updated default settings to include parameters for writing to multiple bots
- Removed code for handling deprecated PT prefixing of enabled_pairs with "ALL_"

Multiple Bots

---

Core/DataObjects/ProfitTrailerData.cs
Monitor/Pages/SalesAnalyzer.cshtml
Monitor/Pages/SalesAnalyzer.cshtml.cs
Monitor/Pages/_get/DashboardBottom.cshtml
Monitor/Pages/_get/DashboardBottom.cshtml.cs
Monitor/Pages/_get/TickerWidgets.cshtml
Monitor/Pages/_get/TickerWidgets.cshtml.cs

- Fixed an issue when calculating profits while shorting.  Old code to calculate profit for individual sales and invert totals was removed, since PT's API now provides all necessary data.

shorting calculations

---

Monitor/Pages/_get/DashboardTop.cshtml

* If "Max Dashboard Buy Entries" is set to "0" (zero) via the GUI or in the file settings.general.json, the Possible Buy List will not be displayed at all in the Dashboard.
* the PBL and PAIRS lists are now both the same width, to compensate for an issue where the PBL renders outside the box when the page zoom is increased.

Optional PBL

---

Core/DataObjects/ProfitTrailerData.cs

Unknown  changes to PT's API data regarding pending orders causes an issue when rendering dashboard.top.
Temporarily fixed by removing pending orders completely, until further investigation and resolution.

remove pending orders

---

Core/Core.csproj
Core/MarketAnalyzer/Binance.cs
Core/MarketAnalyzer/BinanceFutures.cs
Core/MarketAnalyzer/BinanceUS.cs
Monitor/Monitor.csproj
Monitor/Pages/MarketAnalyzer.cshtml
Monitor/Pages/_get/DashboardTop.cshtml
Monitor/Program.cs
PTMagic/PTMagic.csproj
PTMagic/Program.cs

- PTMagic  requires ASP.Net Core Runtime 7.x on the host operating system (download: https://dotnet.microsoft.com/en-us/download/dotnet/7.0)
- Setting "Max Dashboard Buy Entries" to zero, via the gui or editing the settings, will hide the possible buy list in the PTMagic dashboard.  It has no effect on your actual possible buy list in Profit Trailer.
- Increased throttling for the initial collection of market data beyond six hours to avoid IP bans from Binance
- Fixed an issue causing Pending orders to break DashboardTop
- Fixed an issue where coins in Watchmod or Pending were not displaying their current profit value
- Made a change to prevent Pending Buy orders from showing up in the Pairs/DCA/Pending list on DashboardTop
- Any coin pairs, including quarterly futures, that do not end …

Changes for 2.6.1

---

Core/DataObjects/PTMagicData.cs
Monitor/Pages/_get/DashboardBottom.cshtml
Monitor/Pages/_get/DashboardTop.cshtml

viva07 found an error in DashboardTop: If GAIN isn't used as a sell strategy, the value for the variable TargetGain isn't set correctly and creates a null value error.
also removed the word "LIVE" from the TCV trend chart.  Redundant.

Monitor TargetGain Error

---

Core/DataObjects/ProfitTrailerData.cs
PTMagic/Program.cs

Fixes an issue when building monthly sales data for the monitor.
If a month had zero sales, the field AvgGrowth didn't exist in PT's sell record, causing a null object exception.

2.8.5 - empty months
